# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"

# Enhanced AprilTag stop management parameters
enable_apriltag_stops: true
apriltag_stop_distance_threshold: 1.0  # Start stop sequence at 1m
apriltag_stop_duration: 2.0  # Stop for 2 seconds

events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False

# Define nodes
nodes:
  anti_instagram: "anti_instagram_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  ground_projection_node: "ground_projection_node/switch"
  apriltag_detector_node: "apriltag_detector_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  # extras added


# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"
  joystick_override_off: "LANE_FOLLOWING"

states:
  NORMAL_JOYSTICK_CONTROL:
    active_nodes:
      - anti_instagram
      - lane_filter_node
      - line_detector_node
      - ground_projection_node
      - apriltag_detector_node
      - stop_line_filter_node
    lights: "GREEN"
  LANE_FOLLOWING:
    active_nodes:
      - anti_instagram
      - line_detector_node
      - lane_filter_node
      - ground_projection_node
      - apriltag_detector_node
      - stop_line_filter_node
    lights: "CAR_DRIVING"
  APRILTAG_STOP:
    active_nodes:
      - anti_instagram
      - line_detector_node
      - lane_filter_node
      - ground_projection_node
      - apriltag_detector_node
      - stop_line_filter_node
    lights: "RED"
    transitions:
      joystick_override_on: "NORMAL_JOYSTICK_CONTROL"


