# default parameters for lane_filter/lane_filter_node

#propagation
use_propagation: True
debug: True

# Enhanced curve fitting parameters
curve_fitting_enabled: true
polynomial_degree: 2
min_curve_points: 5
extrapolation_distance: 1.0
curve_smoothing_factor: 0.1
curve_history_size: 10

lane_filter_histogram_configuration:
  mean_d_0: 0
  mean_phi_0: 0
  sigma_d_0: 0.1
  sigma_phi_0: 0.1
  delta_d: 0.02
  delta_phi: 0.1
  d_max: 0.3
  d_min: -0.15
  phi_min: -1.5
  phi_max: 1.5
  cov_v: 0.5
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  min_max: 0.1
  sigma_d_mask: 1.0
  sigma_phi_mask: 2.0
  range_min: 0.2
  range_est: 0.33
  range_max: 0.6
